#!/usr/bin/env python3

from pathlib import Path
from sys import argv
import re
import os

if len(argv)!=4:
    print('Usage: replace path oldpattern newpattern')
    exit()

path = argv[1]
oldpattern = argv[2]
newpattern = argv[3]

def traverse_path(path):
    strpath = str(path.absolute())
    if oldpattern in strpath:
        newname = re.sub(oldpattern, newpattern, strpath)
        os.rename(strpath, newname)
        path = Path(newname)
    if path.is_dir(): 
        for entry in path.iterdir():
            traverse_path(entry)
    if path.is_file():
        contents = path.read_text()
        txt = re.sub(oldpattern, newpattern, contents)
        path.write_text(txt)

traverse_path(Path(path))

