#!/usr/bin/env python3

from sys import argv
import os
import shutil

dirpath = "test/edu/bvu/cs/"

if len(argv) > 2:
    print('Usage: run-test (setup|teardown)')
    exit()

if argv[1] == "setup":
    try:
        shutil.rmtree('test/')
    except:
        pass
    finally:
        os.makedirs(dirpath)
        os.chdir(dirpath)
        f1 = open("DevOps.java", "w")
        f1.write('''public class DevOps {
    public DevOps() {
    }
}
    ''')
        f1.close()
        f2 = open("DevOpsMain.java", "w")
        f2.write('''public class DevOpsMain {
    public static void main(String[] args) {
        DevOps dev = new DevOps();
    }
}
    ''')
        f2.close()

elif argv[1] == "teardown":
    try:
        shutil.rmtree('test/')
    except:
        print("That directory doesn't exist")

else:
    print("Usage: run-test (setup|teardown)")
